DROP TABLE ERS_REIMBURSEMENTS;

CREATE TABLE ERS_REIMBURSEMENTS (
        R_ID INTEGER PRIMARY KEY,
        R_AMOUNT NUMBER(22,2) NOT NULL,
        R_DESCRIPTION VARCHAR2(100),
        R_RECEIPT BLOB,
        R_SUBMITTED TIMESTAMP NOT NULL,
        R_RESOLVED TIMESTAMP,
        U_ID_AUTHOR INTEGER NOT NULL,
        U_ID_RESOLVER INTEGER,
        RT_TYPE INTEGER NOT NULL,
        RS_STATUS INTEGER NOT NULL
        );
        
ALTER TABLE ERS_REIMBURSEMENTS ADD CONSTRAINT FK_U_AUTHOR
FOREIGN KEY (U_ID_AUTHOR)
REFERENCES ERS_USERS(U_ID);

ALTER TABLE ERS_REIMBURSEMENTS ADD CONSTRAINT FK_U_RESOLVER
FOREIGN KEY (U_ID_RESOLVER)
REFERENCES ERS_USERS(U_ID);

ALTER TABLE ERS_REIMBURSEMENTS ADD CONSTRAINT FK_RT_TYPE
FOREIGN KEY (RT_TYPE)
REFERENCES ERS_REIMBURSEMENT_TYPE(RT_ID);

ALTER TABLE ERS_REIMBURSEMENTS ADD CONSTRAINT FK_RS_STATUS
FOREIGN KEY (RS_STATUS)
REFERENCES ERS_REIMBURSEMENT_STATUS(RS_ID);